from enum import StrEnum


class EnrichmentStatus(StrEnum):
    PENDING = "PENDING"
    ENRICHED = "ENRICHED"
    INCOMPLETE = "INCOMPLETE"
    FAILED = "FAILED"


class EnrichmentProvider(StrEnum):
    DATASET = "DATASET"
    SCOPUS = "SCOPUS"
    SEMANTIC_SCHOLAR = "SEMANTIC_SCHOLAR"
    OPENALEX = "OPENALEX"
    CROSSREF = "CROSSREF"
    NONE = "NONE"


class ParseStatus(StrEnum):
    PENDING = "PENDING"
    PARSED = "PARSED"
    FAILED = "FAILED"


class ClaimType(StrEnum):
    EMPIRICAL_RESULT = "EMPIRICAL_RESULT"
    FACTUAL_STATEMENT = "FACTUAL_STATEMENT"
    PREVIOUS_RESEARCH = "PREVIOUS_RESEARCH"
    COMPARATIVE_CLAIM = "COMPARATIVE_CLAIM"
    CAUSAL_CLAIM = "CAUSAL_CLAIM"
    DEFINITIONAL_CLAIM = "DEFINITIONAL_CLAIM"
    THEORETICAL_CLAIM = "THEORETICAL_CLAIM"
    METHOD_VALIDATION = "METHOD_VALIDATION"
    STATISTICAL_CLAIM = "STATISTICAL_CLAIM"
    GENERAL_BACKGROUND = "GENERAL_BACKGROUND"
    AUTHOR_CONTRIBUTION = "AUTHOR_CONTRIBUTION"
    NO_CITATION_NEEDED = "NO_CITATION_NEEDED"


class ExistingCitationStatus(StrEnum):
    NO_CITATION_FOUND = "NO_CITATION_FOUND"
    CITATION_EXISTS_NOT_CHECKED = "CITATION_EXISTS_NOT_CHECKED"
    CITATION_EXISTS_AND_SUPPORTED = "CITATION_EXISTS_AND_SUPPORTED"
    CITATION_EXISTS_BUT_WEAK = "CITATION_EXISTS_BUT_WEAK"
    CITATION_EXISTS_AND_CONTRADICTED = "CITATION_EXISTS_AND_CONTRADICTED"


class DetectionMethod(StrEnum):
    RULE = "RULE"
    LLM = "LLM"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    REVIEWED = "REVIEWED"
    DISMISSED = "DISMISSED"


class Verdict(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    TOPICALLY_RELATED_BUT_NOT_EVIDENCE = "TOPICALLY_RELATED_BUT_NOT_EVIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONTRADICTED = "CONTRADICTED"
    # Not an LLM verdict: verification could not be performed at all.
    SKIPPED = "SKIPPED"


#: Verdict -> llm_support_score contribution (spec "Percentage Score").
SUPPORT_SCORE: dict[Verdict, float] = {
    Verdict.SUPPORTED: 1.00,
    Verdict.PARTIALLY_SUPPORTED: 0.65,
    Verdict.TOPICALLY_RELATED_BUT_NOT_EVIDENCE: 0.35,
    Verdict.INSUFFICIENT_EVIDENCE: 0.15,
    Verdict.CONTRADICTED: 0.00,
}


class UserDecision(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    IRRELEVANT = "IRRELEVANT"


class InsertionMode(StrEnum):
    TRACKED_CHANGES = "tracked_changes"
    DIRECT = "direct"
    PLACEHOLDER = "placeholder"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RunStage(StrEnum):
    ENRICHING = "ENRICHING"
    EMBEDDING = "EMBEDDING"
    PARSING = "PARSING"
    CLASSIFYING_SDG = "CLASSIFYING_SDG"
    DETECTING = "DETECTING"
    RECOMMENDING = "RECOMMENDING"


class ExportFormat(StrEnum):
    DOCX = "docx"
    MD = "md"
    CSV = "csv"
    JSON = "json"
