"""exports table and project owner_id

Revision ID: 4bd425984094
Revises: f0740a372b6f
Create Date: 2026-07-28 18:00:11.485686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4bd425984094'
down_revision: Union[str, None] = 'f0740a372b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('citation_style', sa.Text(), server_default='APA', nullable=False),
    sa.Column('insertion_mode', sa.Text(), server_default='tracked_changes', nullable=False),
    sa.Column('include_audit_report', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mismatch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_exports_draft_id_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_exports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'owner_id')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_table('exports')
    # ### end Alembic commands ###
