"""llm_classification_cache table

Revision ID: cb91d38f0d36
Revises: 4bd425984094
Create Date: 2026-08-01 21:11:39.440139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cb91d38f0d36'
down_revision: Union[str, None] = '4bd425984094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_classification_cache',
    sa.Column('sentence_hash', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_classification_cache')),
    sa.UniqueConstraint('sentence_hash', 'model', name=op.f('uq_llm_classification_cache_sentence_hash_model'))
    )
    # ### end Alembic commands ###

    # claim_hash now hashes the source sentence rather than the LLM's
    # paraphrase (claim_detection_service.py). Every existing cache row is
    # keyed on a paraphrase hash that will never be produced again -- it's
    # unreachable, not merely stale. No FK from this table to claims, so
    # there's no integrity concern in clearing it outright.
    op.execute("DELETE FROM llm_verification_cache")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_classification_cache')
    # ### end Alembic commands ###
