"""initial schema

Revision ID: f0740a372b6f
Revises: 
Create Date: 2026-07-28 11:33:38.113846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'f0740a372b6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('citation_style', sa.Text(), server_default='APA', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('drafts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_code', sa.Text(), server_default='en', nullable=False),
    sa.Column('parse_status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_drafts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts'))
    )
    op.create_index(op.f('ix_drafts_project_id'), 'drafts', ['project_id'], unique=False)
    op.create_table('reference_papers',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_row_number', sa.Integer(), nullable=True),
    sa.Column('original_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('scopus_eid', sa.Text(), nullable=True),
    sa.Column('scopus_id', sa.Text(), nullable=True),
    sa.Column('semantic_scholar_id', sa.Text(), nullable=True),
    sa.Column('author_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('index_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('subject_areas', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_link', sa.Text(), nullable=True),
    sa.Column('scopus_url', sa.Text(), nullable=True),
    sa.Column('publisher_url', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('enrichment_provider', sa.Text(), nullable=True),
    sa.Column('enrichment_error', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reference_papers_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_papers'))
    )
    op.create_index('ix_reference_papers_embedding_hnsw', 'reference_papers', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_reference_papers_project_id'), 'reference_papers', ['project_id'], unique=False)
    op.create_index('uq_reference_papers_project_id_doi', 'reference_papers', ['project_id', 'doi'], unique=True, postgresql_where=sa.text('doi IS NOT NULL'))
    op.create_index('uq_reference_papers_project_id_scopus_eid', 'reference_papers', ['project_id', 'scopus_eid'], unique=True, postgresql_where=sa.text('scopus_eid IS NOT NULL'))
    op.create_table('analysis_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_root_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_analysis_runs_draft_id_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_analysis_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('claims',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('sentence_index', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('local_context', sa.Text(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('needs_citation', sa.Boolean(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=True),
    sa.Column('claim_confidence', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.Text(), nullable=True),
    sa.Column('existing_citation_text', sa.Text(), nullable=True),
    sa.Column('existing_citation_status', sa.Text(), server_default='NO_CITATION_FOUND', nullable=False),
    sa.Column('review_status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('claim_hash', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_claims_draft_id_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_claim_hash', 'claims', ['claim_hash'], unique=False)
    op.create_index(op.f('ix_claims_draft_id'), 'claims', ['draft_id'], unique=False)
    op.create_table('llm_verification_cache',
    sa.Column('claim_hash', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_papers.id'], name=op.f('fk_llm_verification_cache_reference_id_reference_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_verification_cache')),
    sa.UniqueConstraint('claim_hash', 'reference_id', name=op.f('uq_llm_verification_cache_claim_hash_reference_id'))
    )
    op.create_table('citation_recommendations',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('lexical_similarity', sa.Float(), nullable=True),
    sa.Column('keyword_overlap', sa.Float(), nullable=True),
    sa.Column('field_match', sa.Float(), nullable=True),
    sa.Column('reranker_score', sa.Float(), nullable=True),
    sa.Column('llm_support_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=False),
    sa.Column('recommendation_label', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('recommended_usage', sa.Text(), nullable=True),
    sa.Column('evidence_paraphrase', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('user_decision', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_citation_recommendations_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_papers.id'], name=op.f('fk_citation_recommendations_reference_id_reference_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation_recommendations')),
    sa.UniqueConstraint('claim_id', 'reference_id', name=op.f('uq_citation_recommendations_claim_id_reference_id'))
    )
    op.create_index(op.f('ix_citation_recommendations_claim_id'), 'citation_recommendations', ['claim_id'], unique=False)
    op.create_table('accepted_citations',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('insertion_format', sa.Text(), nullable=True),
    sa.Column('insertion_mode', sa.Text(), server_default='tracked_changes', nullable=False),
    sa.Column('user_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_accepted_citations_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['citation_recommendations.id'], name=op.f('fk_accepted_citations_recommendation_id_citation_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_papers.id'], name=op.f('fk_accepted_citations_reference_id_reference_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accepted_citations')),
    sa.UniqueConstraint('claim_id', 'reference_id', name=op.f('uq_accepted_citations_claim_id_reference_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accepted_citations')
    op.drop_index(op.f('ix_citation_recommendations_claim_id'), table_name='citation_recommendations')
    op.drop_table('citation_recommendations')
    op.drop_table('llm_verification_cache')
    op.drop_index(op.f('ix_claims_draft_id'), table_name='claims')
    op.drop_index('ix_claims_claim_hash', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('uq_reference_papers_project_id_scopus_eid', table_name='reference_papers', postgresql_where=sa.text('scopus_eid IS NOT NULL'))
    op.drop_index('uq_reference_papers_project_id_doi', table_name='reference_papers', postgresql_where=sa.text('doi IS NOT NULL'))
    op.drop_index(op.f('ix_reference_papers_project_id'), table_name='reference_papers')
    op.drop_index('ix_reference_papers_embedding_hnsw', table_name='reference_papers', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('reference_papers')
    op.drop_index(op.f('ix_drafts_project_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_table('projects')
    # ### end Alembic commands ###
