/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/drafts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Draft */
        post: operations["upload_draft_api_v1_projects__project_id__drafts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_v1_projects__project_id__drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/references/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import References */
        post: operations["import_references_api_v1_projects__project_id__references_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/references/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** References Status */
        get: operations["references_status_api_v1_projects__project_id__references_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List References */
        get: operations["list_references_api_v1_projects__project_id__references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/analysis/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_v1_projects__project_id__analysis_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Status */
        get: operations["analysis_status_api_v1_projects__project_id__analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Summary
         * @description Dashboard data in one call: reference/claim counts, acceptance
         *     coverage, and the latest analysis run's status (if any has run yet).
         */
        get: operations["project_summary_api_v1_projects__project_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_v1_drafts__draft_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommendations */
        get: operations["list_recommendations_api_v1_claims__claim_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations For Draft
         * @description All recommendations for every claim in a draft, in one request --
         *     the review screen would otherwise need one round trip per claim
         *     (55 claims = 55 requests on the real validation paper).
         */
        get: operations["list_recommendations_for_draft_api_v1_drafts__draft_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/accepted-citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accepted Citations For Draft
         * @description claim_id -> the joined citation text ghost text should render, e.g.
         *     "(Smith, 2023; Lee et al., 2024)" when a claim has multiple accepted
         *     references. Kept separate from the recommendations payload since it's
         *     a per-claim aggregate rather than a per-recommendation field.
         */
        get: operations["accepted_citations_for_draft_api_v1_drafts__draft_id__accepted_citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Recommendation Decision */
        post: operations["set_recommendation_decision_api_v1_recommendations__recommendation_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Recommendation */
        post: operations["accept_recommendation_api_v1_recommendations__recommendation_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Recommendation */
        post: operations["reject_recommendation_api_v1_recommendations__recommendation_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_v1_projects__project_id__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_projects__project_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_v1_exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRunAccepted */
        AnalysisRunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Status */
            status: string;
        };
        /** AnalysisRunRequest */
        AnalysisRunRequest: {
            /** Draft Id */
            draft_id?: string | null;
        };
        /** AnalysisRunStatus */
        AnalysisRunStatus: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage: string | null;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            references: components["schemas"]["ReferenceCounts"];
            claims: components["schemas"]["ClaimCounts"];
        };
        /** Body_import_references_api_v1_projects__project_id__references_import_post */
        Body_import_references_api_v1_projects__project_id__references_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_draft_api_v1_projects__project_id__drafts_upload_post */
        Body_upload_draft_api_v1_projects__project_id__drafts_upload_post: {
            /** File */
            file: string;
        };
        /** ClaimCounts */
        ClaimCounts: {
            /** Total */
            total: number;
            /** Needs Citation */
            needs_citation: number;
            /** With Recommendations */
            with_recommendations: number;
        };
        /** ClaimRead */
        ClaimRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Section Title */
            section_title: string | null;
            /** Paragraph Index */
            paragraph_index: number | null;
            /** Sentence Index */
            sentence_index: number | null;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Sentence Text */
            sentence_text: string;
            /** Local Context */
            local_context: string;
            /** Claim Text */
            claim_text: string | null;
            /** Needs Citation */
            needs_citation: boolean;
            /** Claim Type */
            claim_type: string | null;
            /** Claim Confidence */
            claim_confidence: number | null;
            /** Detection Method */
            detection_method: string | null;
            /** Existing Citation Text */
            existing_citation_text: string | null;
            /** Existing Citation Status */
            existing_citation_status: string;
            /** Review Status */
            review_status: string;
            /** Keywords */
            keywords: unknown[] | null;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Note */
            note?: string | null;
        };
        /** DraftDetail */
        DraftDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /** Language Code */
            language_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at: string | null;
            /** Raw Text */
            raw_text: string | null;
            /** Parsed Content */
            parsed_content: {
                [key: string]: unknown;
            } | null;
        };
        /** DraftRead */
        DraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /** Language Code */
            language_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at: string | null;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "docx" | "md" | "csv" | "json";
        /** ExportOutcome */
        ExportOutcome: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Status */
            status: string;
            /** Citation Text */
            citation_text?: string | null;
            /** Paragraph Index */
            paragraph_index?: number | null;
        };
        /** ExportRead */
        ExportRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Format */
            format: string;
            /** Citation Style */
            citation_style: string;
            /** Insertion Mode */
            insertion_mode: string;
            /** Include Audit Report */
            include_audit_report: boolean;
            /** Filename */
            filename: string;
            /** Byte Size */
            byte_size: number;
            /** Inserted Count */
            inserted_count: number;
            /** Mismatch Count */
            mismatch_count: number;
            /** Outcomes */
            outcomes?: components["schemas"]["ExportOutcome"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExportRequest */
        ExportRequest: {
            format: components["schemas"]["ExportFormat"];
            /** Draft Id */
            draft_id?: string | null;
            /**
             * Citation Style
             * @default APA
             */
            citation_style: string;
            /** @default tracked_changes */
            insertion_mode: components["schemas"]["InsertionMode"];
            /**
             * Include Audit Report
             * @default true
             */
            include_audit_report: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped Duplicates */
            skipped_duplicates: number;
            /** Skipped Invalid */
            skipped_invalid: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * InsertionMode
         * @enum {string}
         */
        InsertionMode: "tracked_changes" | "direct" | "placeholder";
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /**
             * Citation Style
             * @default APA
             */
            citation_style: string;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Citation Style */
            citation_style: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectSummary
         * @description Dashboard summary. `coverage_percentage` is computed once here so the
         *     dashboard and any other consumer (export, future reporting) can never
         *     disagree about what "coverage" means.
         */
        ProjectSummary: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Draft Id */
            draft_id: string | null;
            references: components["schemas"]["ReferenceCounts"];
            claims: components["schemas"]["ClaimCounts"];
            /** Accepted Citations */
            accepted_citations: number;
            /** Claims With Accepted */
            claims_with_accepted: number;
            /** Coverage Percentage */
            coverage_percentage: number;
            latest_run: components["schemas"]["AnalysisRunStatus"] | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Citation Style */
            citation_style?: string | null;
        };
        /** RecommendationRead */
        RecommendationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /**
             * Reference Id
             * Format: uuid
             */
            reference_id: string;
            /** Rank */
            rank: number;
            /** Score Percentage */
            score_percentage: number;
            /** Final Score */
            final_score: number;
            /** Recommendation Label */
            recommendation_label: string | null;
            /** Verdict */
            verdict: string;
            /** Recommended Usage */
            recommended_usage: string | null;
            /** Evidence Paraphrase */
            evidence_paraphrase: string | null;
            /** Limitations */
            limitations: string | null;
            /** User Decision */
            user_decision: string;
            /** User Note */
            user_note: string | null;
            score_breakdown: components["schemas"]["ScoreBreakdownOut"];
            reference: components["schemas"]["ReferenceSummary"];
        };
        /** ReferenceCounts */
        ReferenceCounts: {
            /** Total */
            total: number;
            /** Pending */
            pending: number;
            /** Enriched */
            enriched: number;
            /** Incomplete */
            incomplete: number;
            /** Failed */
            failed: number;
            /** Embedded */
            embedded: number;
        };
        /** ReferenceRead */
        ReferenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string | null;
            /** Authors */
            authors: unknown[] | null;
            /** Year */
            year: number | null;
            /** Source Title */
            source_title: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Doi */
            doi: string | null;
            /** Scopus Eid */
            scopus_eid: string | null;
            /** Author Keywords */
            author_keywords: string[] | null;
            /** Index Keywords */
            index_keywords: string[] | null;
            /** Source Link */
            source_link: string | null;
            /** Citation Count */
            citation_count: number | null;
            /** Enrichment Status */
            enrichment_status: string;
            /** Enrichment Provider */
            enrichment_provider: string | null;
            /** Enrichment Error */
            enrichment_error: string | null;
            /** Enriched At */
            enriched_at: string | null;
        };
        /** ReferenceSummary */
        ReferenceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: unknown[] | null;
            /** Year */
            year: number | null;
            /** Source Title */
            source_title: string | null;
            /** Doi */
            doi: string | null;
            /** Scopus Url */
            scopus_url: string | null;
            /** Abstract */
            abstract: string | null;
        };
        /** ScoreBreakdownOut */
        ScoreBreakdownOut: {
            /** Semantic Similarity */
            semantic_similarity: number | null;
            /** Lexical Similarity */
            lexical_similarity: number | null;
            /** Keyword Overlap */
            keyword_overlap: number | null;
            /** Field Match */
            field_match: number | null;
            /** Reranker Score */
            reranker_score: number | null;
            /** Llm Support Score */
            llm_support_score: number | null;
        };
        /**
         * SetDecisionRequest
         * @description Body for the unified /decision endpoint, which accepts any of the
         *     three UserDecision outcomes the review UI can produce. accept/reject
         *     remain as thin aliases hard-coding `decision` for backward compatibility.
         */
        SetDecisionRequest: {
            /** Decision */
            decision: string;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_draft_api_v1_projects__project_id__drafts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_draft_api_v1_projects__project_id__drafts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_projects__project_id__drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_references_api_v1_projects__project_id__references_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_references_api_v1_projects__project_id__references_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    references_status_api_v1_projects__project_id__references_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_references_api_v1_projects__project_id__references_get: {
        parameters: {
            query?: {
                enrichment_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_v1_projects__project_id__analysis_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_status_api_v1_projects__project_id__analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_summary_api_v1_projects__project_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_v1_drafts__draft_id__claims_get: {
        parameters: {
            query?: {
                needs_citation?: boolean | null;
                existing_citation_status?: string | null;
                review_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_v1_claims__claim_id__recommendations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_for_draft_api_v1_drafts__draft_id__recommendations_get: {
        parameters: {
            query?: {
                limit_per_claim?: number;
            };
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["RecommendationRead"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accepted_citations_for_draft_api_v1_drafts__draft_id__accepted_citations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_recommendation_decision_api_v1_recommendations__recommendation_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_recommendation_api_v1_recommendations__recommendation_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recommendation_api_v1_recommendations__recommendation_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_api_v1_projects__project_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_v1_projects__project_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_v1_exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
