/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/drafts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Draft */
        post: operations["upload_draft_api_v1_drafts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_v1_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import References */
        post: operations["import_references_api_v1_library_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Library
         * @description Kick off enrichment-then-embedding for every pending library row.
         *
         *     Not tied to an AnalysisRun -- the library is maintained on its own
         *     schedule, separate from any particular draft's analysis.
         */
        post: operations["refresh_library_api_v1_library_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** References Status */
        get: operations["references_status_api_v1_library_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/missing-abstracts-by-year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Missing Abstracts By Year
         * @description Where to focus manual abstract collection: which publication years
         *     have the most references still missing an abstract, so a user filling
         *     them in by hand (or re-exporting from Scopus) knows where to start.
         */
        get: operations["missing_abstracts_by_year_api_v1_library_missing_abstracts_by_year_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/missing-abstracts-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Missing Abstracts Template
         * @description xlsx of every reference missing an abstract for `year` (omit the
         *     query param for the "unknown year" bucket) -- the header row matches
         *     what /library/import already recognizes, so filling in ABSTRACT and
         *     re-uploading the same file backfills just that field via the normal
         *     duplicate-match path, no separate mechanism needed.
         */
        get: operations["missing_abstracts_template_api_v1_library_missing_abstracts_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List References */
        get: operations["list_references_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/analysis/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_v1_drafts__draft_id__analysis_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Status */
        get: operations["analysis_status_api_v1_drafts__draft_id__analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Draft Summary
         * @description Dashboard data in one call: reference/claim counts, acceptance
         *     coverage, and the latest analysis run's status (if any has run yet).
         */
        get: operations["draft_summary_api_v1_drafts__draft_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_v1_drafts__draft_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommendations */
        get: operations["list_recommendations_api_v1_claims__claim_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations For Draft
         * @description All recommendations for every claim in a draft, in one request --
         *     the review screen would otherwise need one round trip per claim
         *     (55 claims = 55 requests on the real validation paper).
         */
        get: operations["list_recommendations_for_draft_api_v1_drafts__draft_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/best-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Reference For Draft
         * @description The single reference this paper should cite: the highest-scoring
         *     top-ranked recommendation across every claim in the draft. Always
         *     returns the closest match even if it falls below the usable
         *     threshold -- an empty response reads as "broken," not "no reference
         *     is good enough yet," so the caller gets the number and decides.
         */
        get: operations["best_reference_for_draft_api_v1_drafts__draft_id__best_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/best-references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best References For Draft
         * @description The N best references for this paper as a whole -- a ranked
         *     shortlist rather than the single pick /best-reference returns, for
         *     "which references should I actually cite" instead of "give me one."
         *
         *     Mirrors /best-reference's query and threshold logic exactly, just
         *     without the .limit(1): every claim's rank=1 recommendation, ordered by
         *     score. The same reference can legitimately be the strongest match for
         *     more than one claim, so rows are deduped by reference_id (keeping each
         *     reference's highest-scoring claim, since the ordering already put that
         *     one first) before truncating to `limit` -- otherwise a paper with one
         *     dominant reference could fill the whole shortlist with itself.
         */
        get: operations["best_references_for_draft_api_v1_drafts__draft_id__best_references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/accepted-citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accepted Citations For Draft
         * @description claim_id -> the joined citation text ghost text should render, e.g.
         *     "(Smith, 2023; Lee et al., 2024)" when a claim has multiple accepted
         *     references. Kept separate from the recommendations payload since it's
         *     a per-claim aggregate rather than a per-recommendation field.
         */
        get: operations["accepted_citations_for_draft_api_v1_drafts__draft_id__accepted_citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/rewrite-paragraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rewrite Paragraph For Recommendation
         * @description Generate a version of the claim's paragraph with this reference's
         *     citation woven in, plus the bibliography entry to go with it -- for
         *     the "help me actually write the cited paragraph" ask, not just "here
         *     is a reference you could use."
         */
        post: operations["rewrite_paragraph_for_recommendation_api_v1_recommendations__recommendation_id__rewrite_paragraph_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Recommendation Decision */
        post: operations["set_recommendation_decision_api_v1_recommendations__recommendation_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Recommendation */
        post: operations["accept_recommendation_api_v1_recommendations__recommendation_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Recommendation */
        post: operations["reject_recommendation_api_v1_recommendations__recommendation_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_v1_drafts__draft_id__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_drafts__draft_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_v1_exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRunAccepted */
        AnalysisRunAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Status */
            status: string;
        };
        /** AnalysisRunStatus */
        AnalysisRunStatus: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage: string | null;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            references: components["schemas"]["ReferenceCounts"];
            claims: components["schemas"]["ClaimCounts"];
            /** Sdg Number */
            sdg_number?: number | null;
            /** Sdg Name */
            sdg_name?: string | null;
            /** Sdg Keyword */
            sdg_keyword?: string | null;
            /** Sdg Rationale */
            sdg_rationale?: string | null;
            /** Sdg Closest Number */
            sdg_closest_number?: number | null;
            /** Sdg Closest Name */
            sdg_closest_name?: string | null;
        };
        /** BestReferenceClaim */
        BestReferenceClaim: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Section Title */
            section_title: string | null;
            /** Sentence Text */
            sentence_text: string;
            /** Local Context */
            local_context: string;
        };
        /**
         * BestReferenceRead
         * @description The single reference this paper should cite -- one pick across the
         *     whole draft, not one per claim. `meets_threshold`/`is_recommended` let
         *     the UI show *something* even on a weak match rather than a blank page,
         *     while still being honest that it's weak.
         */
        BestReferenceRead: {
            recommendation: components["schemas"]["RecommendationRead"];
            claim: components["schemas"]["BestReferenceClaim"];
            reference: components["schemas"]["ReferenceDetail"];
            /** Meets Threshold */
            meets_threshold: boolean;
            /** Is Recommended */
            is_recommended: boolean;
            /** Min Score Threshold */
            min_score_threshold: number;
            /** Recommended Score Threshold */
            recommended_score_threshold: number;
        };
        /** Body_import_references_api_v1_library_import_post */
        Body_import_references_api_v1_library_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_draft_api_v1_drafts_upload_post */
        Body_upload_draft_api_v1_drafts_upload_post: {
            /** File */
            file: string;
        };
        /** ClaimCounts */
        ClaimCounts: {
            /** Total */
            total: number;
            /** Needs Citation */
            needs_citation: number;
            /** With Recommendations */
            with_recommendations: number;
        };
        /** ClaimRead */
        ClaimRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Section Title */
            section_title: string | null;
            /** Paragraph Index */
            paragraph_index: number | null;
            /** Sentence Index */
            sentence_index: number | null;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Sentence Text */
            sentence_text: string;
            /** Local Context */
            local_context: string;
            /** Claim Text */
            claim_text: string | null;
            /** Needs Citation */
            needs_citation: boolean;
            /** Claim Type */
            claim_type: string | null;
            /** Claim Confidence */
            claim_confidence: number | null;
            /** Detection Method */
            detection_method: string | null;
            /** Existing Citation Text */
            existing_citation_text: string | null;
            /** Existing Citation Status */
            existing_citation_status: string;
            /** Review Status */
            review_status: string;
            /** Keywords */
            keywords: unknown[] | null;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Note */
            note?: string | null;
        };
        /** DraftDetail */
        DraftDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /** Language Code */
            language_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at: string | null;
            /** Raw Text */
            raw_text: string | null;
            /** Parsed Content */
            parsed_content: {
                [key: string]: unknown;
            } | null;
        };
        /** DraftRead */
        DraftRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /** Language Code */
            language_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parsed At */
            parsed_at: string | null;
        };
        /**
         * DraftSummary
         * @description Dashboard summary. `coverage_percentage` is computed once here so the
         *     dashboard and any other consumer (export, future reporting) can never
         *     disagree about what "coverage" means.
         */
        DraftSummary: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            references: components["schemas"]["ReferenceCounts"];
            claims: components["schemas"]["ClaimCounts"];
            /** Accepted Citations */
            accepted_citations: number;
            /** Claims With Accepted */
            claims_with_accepted: number;
            /** Coverage Percentage */
            coverage_percentage: number;
            latest_run: components["schemas"]["AnalysisRunStatus"] | null;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "docx" | "md" | "csv" | "json";
        /** ExportOutcome */
        ExportOutcome: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Status */
            status: string;
            /** Citation Text */
            citation_text?: string | null;
            /** Paragraph Index */
            paragraph_index?: number | null;
        };
        /** ExportRead */
        ExportRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Format */
            format: string;
            /** Citation Style */
            citation_style: string;
            /** Insertion Mode */
            insertion_mode: string;
            /** Include Audit Report */
            include_audit_report: boolean;
            /** Filename */
            filename: string;
            /** Byte Size */
            byte_size: number;
            /** Inserted Count */
            inserted_count: number;
            /** Mismatch Count */
            mismatch_count: number;
            /** Outcomes */
            outcomes?: components["schemas"]["ExportOutcome"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExportRequest */
        ExportRequest: {
            format: components["schemas"]["ExportFormat"];
            /**
             * Citation Style
             * @default APA
             */
            citation_style: string;
            /** @default tracked_changes */
            insertion_mode: components["schemas"]["InsertionMode"];
            /**
             * Include Audit Report
             * @default true
             */
            include_audit_report: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped Duplicates */
            skipped_duplicates: number;
            /** Skipped Invalid */
            skipped_invalid: number;
            /** Backfilled Abstracts */
            backfilled_abstracts: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * InsertionMode
         * @enum {string}
         */
        InsertionMode: "tracked_changes" | "direct" | "placeholder";
        /** MissingAbstractsByYear */
        MissingAbstractsByYear: {
            /** Year */
            year: number | null;
            /** Missing */
            missing: number;
            /** Total */
            total: number;
        };
        /** ParagraphRewriteRead */
        ParagraphRewriteRead: {
            /** Paragraph */
            paragraph: string;
            /** In Text Citation */
            in_text_citation: string;
            /** Bibliography Entry */
            bibliography_entry: string;
            /** Style */
            style: string;
        };
        /** ParagraphRewriteRequest */
        ParagraphRewriteRequest: {
            /**
             * Style
             * @default APA
             */
            style: string;
        };
        /** RecommendationRead */
        RecommendationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /**
             * Reference Id
             * Format: uuid
             */
            reference_id: string;
            /** Rank */
            rank: number;
            /** Score Percentage */
            score_percentage: number;
            /** Final Score */
            final_score: number;
            /** Recommendation Label */
            recommendation_label: string | null;
            /** Verdict */
            verdict: string;
            /** Recommended Usage */
            recommended_usage: string | null;
            /** Evidence Paraphrase */
            evidence_paraphrase: string | null;
            /** Limitations */
            limitations: string | null;
            /** User Decision */
            user_decision: string;
            /** User Note */
            user_note: string | null;
            score_breakdown: components["schemas"]["ScoreBreakdownOut"];
            reference: components["schemas"]["ReferenceSummary"];
        };
        /** ReferenceCounts */
        ReferenceCounts: {
            /** Total */
            total: number;
            /** Pending */
            pending: number;
            /** Enriched */
            enriched: number;
            /** Incomplete */
            incomplete: number;
            /** Failed */
            failed: number;
            /** Embedded */
            embedded: number;
        };
        /**
         * ReferenceDetail
         * @description The fuller "view details of the chosen paper" picture -- everything
         *     ReferenceSummary has, plus the fields only worth showing once a paper
         *     has actually been singled out as the one to cite.
         */
        ReferenceDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: unknown[] | null;
            /** Year */
            year: number | null;
            /** Source Title */
            source_title: string | null;
            /** Doi */
            doi: string | null;
            /** Scopus Url */
            scopus_url: string | null;
            /** Abstract */
            abstract: string | null;
            /** Source Link */
            source_link: string | null;
            /** Citation Count */
            citation_count: number | null;
            /** Document Type */
            document_type: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Author Keywords */
            author_keywords: string[] | null;
            /** Index Keywords */
            index_keywords: string[] | null;
            /** Subject Areas */
            subject_areas: string[] | null;
            /** Publisher Url */
            publisher_url: string | null;
        };
        /** ReferenceRead */
        ReferenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string | null;
            /** Authors */
            authors: unknown[] | null;
            /** Year */
            year: number | null;
            /** Source Title */
            source_title: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Doi */
            doi: string | null;
            /** Scopus Eid */
            scopus_eid: string | null;
            /** Author Keywords */
            author_keywords: string[] | null;
            /** Index Keywords */
            index_keywords: string[] | null;
            /** Source Link */
            source_link: string | null;
            /** Citation Count */
            citation_count: number | null;
            /** Enrichment Status */
            enrichment_status: string;
            /** Enrichment Provider */
            enrichment_provider: string | null;
            /** Enrichment Error */
            enrichment_error: string | null;
            /** Enriched At */
            enriched_at: string | null;
        };
        /** ReferenceSummary */
        ReferenceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: unknown[] | null;
            /** Year */
            year: number | null;
            /** Source Title */
            source_title: string | null;
            /** Doi */
            doi: string | null;
            /** Scopus Url */
            scopus_url: string | null;
            /** Abstract */
            abstract: string | null;
        };
        /** ScoreBreakdownOut */
        ScoreBreakdownOut: {
            /** Semantic Similarity */
            semantic_similarity: number | null;
            /** Lexical Similarity */
            lexical_similarity: number | null;
            /** Keyword Overlap */
            keyword_overlap: number | null;
            /** Field Match */
            field_match: number | null;
            /** Reranker Score */
            reranker_score: number | null;
            /** Llm Support Score */
            llm_support_score: number | null;
        };
        /**
         * SetDecisionRequest
         * @description Body for the unified /decision endpoint, which accepts any of the
         *     three UserDecision outcomes the review UI can produce. accept/reject
         *     remain as thin aliases hard-coding `decision` for backward compatibility.
         */
        SetDecisionRequest: {
            /** Decision */
            decision: string;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_draft_api_v1_drafts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_draft_api_v1_drafts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"][];
                };
            };
        };
    };
    get_draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_references_api_v1_library_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_references_api_v1_library_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_library_api_v1_library_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    references_status_api_v1_library_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCounts"];
                };
            };
        };
    };
    missing_abstracts_by_year_api_v1_library_missing_abstracts_by_year_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingAbstractsByYear"][];
                };
            };
        };
    };
    missing_abstracts_template_api_v1_library_missing_abstracts_template_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_references_api_v1_library_get: {
        parameters: {
            query?: {
                enrichment_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_v1_drafts__draft_id__analysis_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_status_api_v1_drafts__draft_id__analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_summary_api_v1_drafts__draft_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_v1_drafts__draft_id__claims_get: {
        parameters: {
            query?: {
                needs_citation?: boolean | null;
                existing_citation_status?: string | null;
                review_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_v1_claims__claim_id__recommendations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_for_draft_api_v1_drafts__draft_id__recommendations_get: {
        parameters: {
            query?: {
                limit_per_claim?: number;
            };
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["RecommendationRead"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_reference_for_draft_api_v1_drafts__draft_id__best_reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestReferenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_references_for_draft_api_v1_drafts__draft_id__best_references_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestReferenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accepted_citations_for_draft_api_v1_drafts__draft_id__accepted_citations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_paragraph_for_recommendation_api_v1_recommendations__recommendation_id__rewrite_paragraph_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParagraphRewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParagraphRewriteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_recommendation_decision_api_v1_recommendations__recommendation_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_recommendation_api_v1_recommendations__recommendation_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recommendation_api_v1_recommendations__recommendation_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_api_v1_drafts__draft_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_v1_drafts__draft_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_v1_exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
